online-test/routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('questions', 'Admin\QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'Admin\QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::post('questions_restore/{id}', ['uses' => 'Admin\QuestionsController@restore', 'as' => 'questions.restore']);
    Route::delete('questions_perma_del/{id}', ['uses' => 'Admin\QuestionsController@perma_del', 'as' => 'questions.perma_del']);
    Route::resource('question_options', 'Admin\QuestionOptionsController');
    Route::post('question_options_mass_destroy', ['uses' => 'Admin\QuestionOptionsController@massDestroy', 'as' => 'question_options.mass_destroy']);
    Route::post('question_options_restore/{id}', ['uses' => 'Admin\QuestionOptionsController@restore', 'as' => 'question_options.restore']);
    Route::delete('question_options_perma_del/{id}', ['uses' => 'Admin\QuestionOptionsController@perma_del', 'as' => 'question_options.perma_del']);
    Route::resource('tests', 'Admin\TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'Admin\TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::post('tests_restore/{id}', ['uses' => 'Admin\TestsController@restore', 'as' => 'tests.restore']);
    Route::delete('tests_perma_del/{id}', ['uses' => 'Admin\TestsController@perma_del', 'as' => 'tests.perma_del']);



 
});

online-test/app/QuestionOption.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class QuestionOption
 *
 * @package App
 * @property text $option_text
 * @property tinyInteger $correct
*/
class QuestionOption extends Model
{
    use SoftDeletes;

    protected $fillable = ['option_text', 'correct'];
    protected $hidden = [];
    
    
    
    public function question()
    {
        return $this->belongsToMany(Question::class, 'question_question_option')->withTrashed();
    }
    
}

online-test/app/Http/Controllers/Admin/QuestionOptionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\QuestionOption;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreQuestionOptionsRequest;
use App\Http\Requests\Admin\UpdateQuestionOptionsRequest;

class QuestionOptionsController extends Controller
{
    /**
     * Display a listing of QuestionOption.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('question_option_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('question_option_delete')) {
                return abort(401);
            }
            $question_options = QuestionOption::onlyTrashed()->get();
        } else {
            $question_options = QuestionOption::all();
        }

        return view('admin.question_options.index', compact('question_options'));
    }

    /**
     * Show the form for creating new QuestionOption.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('question_option_create')) {
            return abort(401);
        }
        
        $questions = \App\Question::get()->pluck('question', 'id');


        return view('admin.question_options.create', compact('questions'));
    }

    /**
     * Store a newly created QuestionOption in storage.
     *
     * @param  \App\Http\Requests\StoreQuestionOptionsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionOptionsRequest $request)
    {
        if (! Gate::allows('question_option_create')) {
            return abort(401);
        }
        $question_option = QuestionOption::create($request->all());
        $question_option->question()->sync(array_filter((array)$request->input('question')));



        return redirect()->route('admin.question_options.index');
    }


    /**
     * Show the form for editing QuestionOption.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('question_option_edit')) {
            return abort(401);
        }
        
        $questions = \App\Question::get()->pluck('question', 'id');


        $question_option = QuestionOption::findOrFail($id);

        return view('admin.question_options.edit', compact('question_option', 'questions'));
    }

    /**
     * Update QuestionOption in storage.
     *
     * @param  \App\Http\Requests\UpdateQuestionOptionsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionOptionsRequest $request, $id)
    {
        if (! Gate::allows('question_option_edit')) {
            return abort(401);
        }
        $question_option = QuestionOption::findOrFail($id);
        $question_option->update($request->all());
        $question_option->question()->sync(array_filter((array)$request->input('question')));



        return redirect()->route('admin.question_options.index');
    }


    /**
     * Display QuestionOption.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('question_option_view')) {
            return abort(401);
        }
        $question_option = QuestionOption::findOrFail($id);

        return view('admin.question_options.show', compact('question_option'));
    }


    /**
     * Remove QuestionOption from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('question_option_delete')) {
            return abort(401);
        }
        $question_option = QuestionOption::findOrFail($id);
        $question_option->delete();

        return redirect()->route('admin.question_options.index');
    }

    /**
     * Delete all selected QuestionOption at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('question_option_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = QuestionOption::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore QuestionOption from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('question_option_delete')) {
            return abort(401);
        }
        $question_option = QuestionOption::onlyTrashed()->findOrFail($id);
        $question_option->restore();

        return redirect()->route('admin.question_options.index');
    }

    /**
     * Permanently delete QuestionOption from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('question_option_delete')) {
            return abort(401);
        }
        $question_option = QuestionOption::onlyTrashed()->findOrFail($id);
        $question_option->forceDelete();

        return redirect()->route('admin.question_options.index');
    }
}

online-test/resources/views/admin/question_options/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.question-options.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.question_options.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', trans('quickadmin.question-options.fields.question').'', ['class' => 'control-label']) !!}
                    <button type="button" class="btn btn-primary btn-xs" id="selectbtn-question">
                        {{ trans('quickadmin.qa_select_all') }}
                    </button>
                    <button type="button" class="btn btn-primary btn-xs" id="deselectbtn-question">
                        {{ trans('quickadmin.qa_deselect_all') }}
                    </button>
                    {!! Form::select('question[]', $questions, old('question'), ['class' => 'form-control select2', 'multiple' => 'multiple', 'id' => 'selectall-question' ]) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('option_text', trans('quickadmin.question-options.fields.option-text').'*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('option_text', old('option_text'), ['class' => 'form-control ', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('option_text'))
                        <p class="help-block">
                            {{ $errors->first('option_text') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('correct', trans('quickadmin.question-options.fields.correct').'', ['class' => 'control-label']) !!}
                    {!! Form::hidden('correct', 0) !!}
                    {!! Form::checkbox('correct', 1, old('correct', false), []) !!}
                    <p class="help-block"></p>
                    @if($errors->has('correct'))
                        <p class="help-block">
                            {{ $errors->first('correct') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script>
        $("#selectbtn-question").click(function(){
            $("#selectall-question > option").prop("selected","selected");
            $("#selectall-question").trigger("change");
        });
        $("#deselectbtn-question").click(function(){
            $("#selectall-question > option").prop("selected","");
            $("#selectall-question").trigger("change");
        });
    </script>
@stop

online-test/resources/views/admin/question_options/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.question-options.title')</h3>
    
    {!! Form::model($question_option, ['method' => 'PUT', 'route' => ['admin.question_options.update', $question_option->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', trans('quickadmin.question-options.fields.question').'', ['class' => 'control-label']) !!}
                    <button type="button" class="btn btn-primary btn-xs" id="selectbtn-question">
                        {{ trans('quickadmin.qa_select_all') }}
                    </button>
                    <button type="button" class="btn btn-primary btn-xs" id="deselectbtn-question">
                        {{ trans('quickadmin.qa_deselect_all') }}
                    </button>
                    {!! Form::select('question[]', $questions, old('question') ? old('question') : $question_option->question->pluck('id')->toArray(), ['class' => 'form-control select2', 'multiple' => 'multiple', 'id' => 'selectall-question' ]) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('option_text', trans('quickadmin.question-options.fields.option-text').'*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('option_text', old('option_text'), ['class' => 'form-control ', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('option_text'))
                        <p class="help-block">
                            {{ $errors->first('option_text') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('correct', trans('quickadmin.question-options.fields.correct').'', ['class' => 'control-label']) !!}
                    {!! Form::hidden('correct', 0) !!}
                    {!! Form::checkbox('correct', 1, old('correct', old('correct')), []) !!}
                    <p class="help-block"></p>
                    @if($errors->has('correct'))
                        <p class="help-block">
                            {{ $errors->first('correct') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent

    <script>
        $("#selectbtn-question").click(function(){
            $("#selectall-question > option").prop("selected","selected");
            $("#selectall-question").trigger("change");
        });
        $("#deselectbtn-question").click(function(){
            $("#selectall-question > option").prop("selected","");
            $("#selectall-question").trigger("change");
        });
    </script>
@stop

online-test/resources/views/admin/question_options/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.question-options.title')</h3>
    @can('question_option_create')
    <p>
        <a href="{{ route('admin.question_options.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    @can('question_option_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.question_options.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.question_options.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($question_options) > 0 ? 'datatable' : '' }} @can('question_option_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('question_option_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.question-options.fields.question')</th>
                        <th>@lang('quickadmin.question-options.fields.option-text')</th>
                        <th>@lang('quickadmin.question-options.fields.correct')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($question_options) > 0)
                        @foreach ($question_options as $question_option)
                            <tr data-entry-id="{{ $question_option->id }}">
                                @can('question_option_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='question'>
                                    @foreach ($question_option->question as $singleQuestion)
                                        <span class="label label-info label-many">{{ $singleQuestion->question }}</span>
                                    @endforeach
                                </td>
                                <td field-key='option_text'>{!! $question_option->option_text !!}</td>
                                <td field-key='correct'>{{ Form::checkbox("correct", 1, $question_option->correct == 1 ? true : false, ["disabled"]) }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('question_option_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.question_options.restore', $question_option->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('question_option_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.question_options.perma_del', $question_option->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('question_option_view')
                                    <a href="{{ route('admin.question_options.show',[$question_option->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('question_option_edit')
                                    <a href="{{ route('admin.question_options.edit',[$question_option->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('question_option_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.question_options.destroy', $question_option->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="8">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('question_option_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.question_options.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

online-test/resources/views/admin/question_options/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.question-options.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.question-options.fields.question')</th>
                            <td field-key='question'>
                                @foreach ($question_option->question as $singleQuestion)
                                    <span class="label label-info label-many">{{ $singleQuestion->question }}</span>
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.question-options.fields.option-text')</th>
                            <td field-key='option_text'>{!! $question_option->option_text !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.question-options.fields.correct')</th>
                            <td field-key='correct'>{{ Form::checkbox("correct", 1, $question_option->correct == 1 ? true : false, ["disabled"]) }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.question_options.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop